### ISSUE TITLE
Textmate 2 alpha compatibility? :)

### ISSUE THREAD

**Issue by jmonster** [ThisIsMissEm/jade-tmbundle#17]

**Comment by wavoemployee25** [comment]
Bump!

**Comment by jgoodall** [comment]
seems to work:

mkdir -p ~/Library/Application\ Support/Avian/Pristine\ Copy/Bundles
cd ~/Library/Application\ Support/Avian/Pristine\ Copy/Bundles
git clone https://github.com/miksago/jade-tmbundle Jade.tmbundle

**Comment by Hoverbear** [comment]
It works now, this issue can be closed.
